### ISSUE TITLE
add_color_settings_parameter Bookmap critical error 

### ISSUE THREAD

**Issue by IperGiove** [BookmapAPI/python-api#5]
The function add_color_settings_parameter has an error, because when it is called a critical error from Bookmap appears.
This is the script to test the error:

```python
import pyl1api as bm

REQ_ID = 1

    
def handle_subscribe_instrument(addon, alias, full_name, is_crypto, pips, size_multiplier, instrument_multiplier):
    global REQ_ID
    bm.register_indicator(
        addon=addon, 
        alias=alias, 
        req_id=REQ_ID, 
        indicator_name="test indicator",
        graph_type="PRIMARY", 
        color=(0, 0, 0)
    )
    bm.subscribe_to_depth(addon, alias, REQ_ID)
    
    bm.add_color_settings_parameter(
        addon=addon, 
        alias=alias, 
        parameter_name="Parameter Name", 
        default_value=(0,0,0), 
    )
                

def handle_unsubscribe_instrument(addon, alias):
    """
    unsubscribe
    """


if __name__ == "__main__":
    addon = bm.create_addon()
    bm.start_addon(addon, handle_subscribe_instrument, handle_unsubscribe_instrument)
    bm.wait_until_addon_is_turned_off(addon)
```

The error is:

```bash
ERROR: error msg
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at com.bookmap.api.rpc.server.addon.RpcSettings$SettingsParameter.lambda$getValue$0(SourceFile:102)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.bookmap.api.rpc.server.addon.RpcSettings$SettingsParameter.getValue(SourceFile:102)
	at com.bookmap.api.rpc.server.c.a.a(SourceFile:81)
	at com.bookmap.api.rpc.server.c.a.b(SourceFile:54)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at velox.ib.N.dispatchEvent(SourceFile:73)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nyckyta** [comment]
Thank you for the report. I will take a look to the issue shortly.

**Comment by nyckyta** [comment]
I was able to reproduce the issue. Thank you for the report. I will try to fix shortly
